reset;

option solver cplex;
option cplex_options "time=180";

#param MIN_AVERAGE_INCOME;

model task.mod;
data parameters.dat;

param MIN_DETERMINED_INCOME = -200;
param MAX_DETERMINED_INCOME = 12000;

param SAMPLES = 119;

param STEP := (MAX_DETERMINED_INCOME - MIN_DETERMINED_INCOME) / (SAMPLES - 1);

for {i in 0..(SAMPLES - 1)} {
    let MIN_AVERAGE_INCOME := MIN_DETERMINED_INCOME + i * STEP;
    solve;
    display MIN_AVERAGE_INCOME;
    display average_income;
    display mad_risk;
}
